#######################################################################	
all: normalize_vec.exec
#######################################################################	

normalize_vec.exec : normalize_vec.cpp
	g++ normalize_vec.cpp -fopenmp -o normalize_vec.exec

#######################################################################	
	
clean :
	rm -f *.exec